<?php

/**
 * @file
 * Provides marucha's hooks.
 */

use Drupal\marucha\Event\MaruchaEvents;
use Drupal\marucha\Event\MaruchaFirstEvent;
use Drupal\user\UserInterface;

/**
 * Implements hook_user_login().
 */
function marucha_user_login(UserInterface $account) {
  $event = new MaruchaFirstEvent($account);
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, MaruchaEvents::FIRST_EVENT);
}
